name: Go CI

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download

      - name: Lint (go vet)
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v

      - name: Build
        run: go build ./...
